### ISSUE TITLE
npx tsc error also their is no settings.json or config.json  

### ISSUE THREAD

**Issue by xzakier** [voltflake/video-bot#2]
`npx tsc
src/main.ts:37:27 - error TS2339: Property 'sendTyping' does not exist on type 'DMChannel | PartialDMChannel | NewsChannel | StageChannel | TextChannel | PrivateThreadChannel | PublicThreadChannel<...> | VoiceChannel'.
  Property 'sendTyping' does not exist on type 'StageChannel'.

37     await message.channel.sendTyping();
                             ~~~~~~~~~~

src/main.ts:39:29 - error TS2339: Property 'sendTyping' does not exist on type 'DMChannel | PartialDMChannel | NewsChannel | StageChannel | TextChannel | PrivateThreadChannel | PublicThreadChannel<...> | VoiceChannel'.
  Property 'sendTyping' does not exist on type 'StageChannel'.

39       await message.channel.sendTyping();
                               ~~~~~~~~~~

Found 2 errors in the same file, starting at: src/main.ts:37
`

**Comment by voltflake** [comment]
Probably **Discord.js** was updated, I'll try to fix this today.

**Comment by voltflake** [comment]
I'll update that too, looks like I forgot to port it back to node.js from deno.

**Comment by voltflake** [comment]
I pushed a fix, try it out. Let me know if you still have issues.

**Comment by voltflake** [comment]
bot should automatically guide you through settings and create appropriate settings.json. 
to run bot just execute `node .` in project directory

**Comment by voltflake** [comment]
> and another question you mean node main.js not node index.js right ?
entry point is `./out/main.js` actually. I need to update readme file too, good point!

**Comment by voltflake** [comment]
I updated project readme file and added `vt.tiktok` link support. Glad it now works for you!
Also are `vm.` and `vt.` the only links tiktok makes or there are more?

**Comment by voltflake** [comment]
Thanks a lot.
> I all most tried all git hub projects, non of them worked

That is exactly the reason why I created my own repo/bot!

**Comment by voltflake** [comment]
Have you updated `main.ts` file? You also need to re-build bot using `npx tsc` command after updating `main.ts`.

**Comment by voltflake** [comment]
> I well chick all countries on my VPN and all devices ant try to make a list for you by tomorrow if there is any more subdomains, and again you really saved me I all most tried all git hub projects, non of them worked.

No need to check for other countries. I added support for any tiktok.com subdomain.  https://regex101.com/r/DdBzp7/1
