### ISSUE TITLE
gallery-dl cookies

### ISSUE THREAD

**Issue by xzakier** [voltflake/video-bot#3]
`Error when getting video data: Can't extract video from instagram url after 3 tries:
Error #1: extracting raw video failed: gallery-dl error, check cookies
Error #2: extracting raw video failed: gallery-dl error, check cookies
Error #3: extracting raw video failed: gallery-dl error, check cookies`

*only for instagram urls

*hosting on Aws EC2

**Comment by voltflake** [comment]
Yes, you need to log into an instagram account using cookies to download instagram videos.
If you use firefox, install [this extension](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt) and log into instagram account. Once on main page click "export site cookies to file". Place that file in bot directory and it should work.

Also make sure gallery-dl is installed on machine hosting bot.

**Comment by voltflake** [comment]
whatever you prefer, important thing is that you should be able to call it from terminal using `gallery-dl`.

**Comment by voltflake** [comment]
In directory where you launch node. If you use **node .** then project directory, not out.

**Comment by voltflake** [comment]
Yeah, I made a lot of changes and added many features without updating readme because I only needed stuff for my discord server. I'll update readme properly soon for everyone on github. Cheers!
